services:
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - gai-net

  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - gai-net

networks:
  gai-net:
