# configs/inference_config.yaml

# Model Configuration
model_base: "runwayml/stable-diffusion-v1-5"
model_dir: "outputs"
task_name: "dug_toy_dreambooth"

# Model Paths
unet_path: "outputs/duck_toy_dreambooth/unet_final.pt"
text_encoder_path: "outputs/duck_toy_dreambooth/text_encoder_final.pt"

# Output Configuration
output_dir: "inference_outputs/dug_toy_dreambooth/inference_results"
output_path: "inference_outputs/dug_toy_dreambooth/inference_results/generated.png"

# Generation Parameters
prompt: "a photo of brux duck toy in near ocean with waterfall"
num_steps: 100
guidance_scale: 7.5
seed: 42