# configs/inference_config.yaml

# Model Configuration
model_base: "runwayml/stable-diffusion-v1-5"
model_dir: "outputs"
task_name: "monster_toy_dreambooth"

# Model Paths
unet_path: "outputs/monster_toy_dreambooth/unet_final.pt"
text_encoder_path: "outputs/monster_toy_dreambooth/text_encoder_final.pt"

# Output Configuration
output_dir: "inference_outputs/monster_toy_dreambooth/inference_results"
output_path: "inference_outputs/monster_toy_dreambooth/inference_results/generated.png"

# Generation Parameters
prompt: "a photo of a miff monster toy in the ocean with ship in the background"
num_steps: 100
guidance_scale: 7.5
seed: 42

# a miff monster toy in car

# a miff monster red toy with sunglasses